//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAY.DAL.ServiceMethod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMethod.IServerMethod")]
    public interface IServerMethod {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerMethod/RequestChangePassword", ReplyAction="http://tempuri.org/IServerMethod/RequestChangePasswordResponse")]
        string RequestChangePassword(string IDUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerMethodChannel : JAY.DAL.ServiceMethod.IServerMethod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerMethodClient : System.ServiceModel.ClientBase<JAY.DAL.ServiceMethod.IServerMethod>, JAY.DAL.ServiceMethod.IServerMethod {
        
        public ServerMethodClient() {
        }
        
        public ServerMethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerMethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerMethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerMethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RequestChangePassword(string IDUser) {
            return base.Channel.RequestChangePassword(IDUser);
        }
    }
}
