//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckFPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiches
    {
        public int ID { get; set; }
        public string NumFiche { get; set; }
        public string RefMT { get; set; }
        public string RefMO { get; set; }
        public string RefSIM { get; set; }
        public bool IsCompiled { get;
            set; }
        public string VerIDialog { get; set; }
        public Nullable<System.DateTime> DateMiseADispo { get; set; }
        public Nullable<System.DateTime> DateLastCompile { get; set; }
        public string VersionFiche { get; set; }
        public Nullable<int> IDComplement { get; set; }
        public string PresenceIR { get; set; }
        public Nullable<int> TypeFiche { get; set; }
        public Nullable<int> OptionIR { get; set; }
        public Nullable<int> OptionExploit { get; set; }
        public Nullable<int> AnyBus { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string NomClient { get; set; }
        public byte[] DateMAJ { get; set; }
        public string Indice { get; set; }
        public Nullable<int> TypeSynchro { get; set; }
        public Nullable<int> ErrorCheck { get; set; }
        public Nullable<System.DateTime> DateCheck { get; set; }
        public Nullable<int> MTdebit { get; set; }
        public Nullable<int> MOdebit { get; set; }
        public Nullable<short> D30110 { get; set; }
        public Nullable<short> D30120 { get; set; }
        public Nullable<short> D30130 { get; set; }
        public Nullable<short> D30140 { get; set; }
        public Nullable<short> D30150 { get; set; }
        public Nullable<short> D30330 { get; set; }
        public Nullable<short> D30480 { get; set; }
        public Nullable<short> D30400A { get; set; }
        public Nullable<short> D30430A { get; set; }
        public Nullable<short> D30440A { get; set; }
        public Nullable<short> D30450A { get; set; }
        public Nullable<short> D30460A { get; set; }
        public Nullable<short> D30470A { get; set; }
        public Nullable<short> D30840A { get; set; }
        public Nullable<short> D30490A { get; set; }
        public Nullable<int> LiaisonFilaire { get; set; }
        public Nullable<short> D30220A { get; set; }
    }
}
