//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckFPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuiviMAJ
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LastMAJ { get; set; }
        public string Error { get; set; }
    }
}
