//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateurDFUSafir.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jayelectronique.
        /// </summary>
        public static string DomaineAccesReseau {
            get {
                return ResourceManager.GetString("DomaineAccesReseau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CLTPROD.
        /// </summary>
        public static string DOSSIER_IMPORT {
            get {
                return ResourceManager.GetString("DOSSIER_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à data source=CXWFRSAI-SV0197\SAGEX3V12;initial catalog=x112p;persist security info=True;user id=CLTPROD;password=8hpyY6m9HpdY;multipleactiveresultsets=True;encrypt=true;trustServerCertificate=true.
        /// </summary>
        public static string ERPString {
            get {
                return ResourceManager.GetString("ERPString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JAY électronique F-38330 St Ismier.
        /// </summary>
        public static string FOURNISSEUR {
            get {
                return ResourceManager.GetString("FOURNISSEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 433...434.79 MHz.
        /// </summary>
        public static string INFO_433 {
            get {
                return ResourceManager.GetString("INFO_433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 869.7...870. MHz.
        /// </summary>
        public static string INFO_869 {
            get {
                return ResourceManager.GetString("INFO_869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 911.8...918.2 MHz.
        /// </summary>
        public static string INFO_911 {
            get {
                return ResourceManager.GetString("INFO_911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\DONNEES_PRODUCTION\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\stock\logistique.lab.
        /// </summary>
        public static string LABELNAME_BAC {
            get {
                return ResourceManager.GetString("LABELNAME_BAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\donnees_production\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\Emballage DATAMATRIX x2.Lab.
        /// </summary>
        public static string LABELNAME_DATAMATRIX {
            get {
                return ResourceManager.GetString("LABELNAME_DATAMATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\DONNEES_PRODUCTION\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\UD\FabUDE.lab.
        /// </summary>
        public static string LABELNAME_FABUDE {
            get {
                return ResourceManager.GetString("LABELNAME_FABUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\DONNEES_PRODUCTION\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\NC_PROD.lab.
        /// </summary>
        public static string LABELNAME_PNC {
            get {
                return ResourceManager.GetString("LABELNAME_PNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\DONNEES_PRODUCTION\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\UD\planche_UDE.lab.
        /// </summary>
        public static string LABELNAME_UDE {
            get {
                return ResourceManager.GetString("LABELNAME_UDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\DONNEES_PRODUCTION\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_Models\UD\FCC_915.lab.
        /// </summary>
        public static string LABELNAME_UDE_FCC {
            get {
                return ResourceManager.GetString("LABELNAME_UDE_FCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à product.
        /// </summary>
        public static string LoginAccesReseau {
            get {
                return ResourceManager.GetString("LoginAccesReseau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BRADY BP-PR 300 plus PEGASE.
        /// </summary>
        public static string MoNomImprimanteEtiquette {
            get {
                return ResourceManager.GetString("MoNomImprimanteEtiquette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E:\Sage\X3U12PROD\dossiers\CLTPROD\EXTBATCH\job\.
        /// </summary>
        public static string NOMJAY {
            get {
                return ResourceManager.GetString("NOMJAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CDC43F6FA4E98675CBB561D9.
        /// </summary>
        public static string PASS {
            get {
                return ResourceManager.GetString("PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2017Pr01.
        /// </summary>
        public static string PasswordAccesReseau {
            get {
                return ResourceManager.GetString("PasswordAccesReseau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IF35247.
        /// </summary>
        public static string PCPRODUCTION {
            get {
                return ResourceManager.GetString("PCPRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ^( (([0-9]{1,2} ?x ?)?(([A-Z0-9]{04} ?)|(E[1-9]{1,2})) ?,? ?)*|(((([A-Z0-9]{4})|(E[1-9]{1,2})) ?, ?)*(([A-Z0-9]{4})|(E[1-9]{1,2}))) ?,? ?)$.
        /// </summary>
        public static string regex_multi_codeid {
            get {
                return ResourceManager.GetString("regex_multi_codeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\donnees_production\DONNEES_INDUSTRIELLES\DOSSIER OUTIL\GENERATEURDFU\JOB.
        /// </summary>
        public static string REP_JOB {
            get {
                return ResourceManager.GetString("REP_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\jaysvrz2\.
        /// </summary>
        public static string REP_SCRIPT_X3 {
            get {
                return ResourceManager.GetString("REP_SCRIPT_X3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\donnees_production\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_scrutation.
        /// </summary>
        public static string REP_SCRUTATION {
            get {
                return ResourceManager.GetString("REP_SCRUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\Jaysvrfiles\donnees_production\DONNEES_INDUSTRIELLES\ETIQUETTES\Etiquettes_scrutation2.
        /// </summary>
        public static string REP_SCRUTATION2 {
            get {
                return ResourceManager.GetString("REP_SCRUTATION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMP.
        /// </summary>
        public static string UTIL {
            get {
                return ResourceManager.GetString("UTIL", resourceCulture);
            }
        }
    }
}
