//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// Nom du fichier d'origine :
// Date de génération : 14/04/2025 12:38:59
namespace JAY.DAL.ServiceData
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour PEGASE_SUPPORTEntities dans le schéma.
    /// </summary>
    public partial class PEGASE_SUPPORTEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisez un nouvel objet PEGASE_SUPPORTEntities.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PEGASE_SUPPORTEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ServerData", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("JAY.DAL.ServiceData", typeName.Substring(10)), false);
            }
            return null;
        }
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("JAY.DAL.ServiceData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ServerData.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour SimPROJECT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SimPROJECT> SimPROJECT
        {
            get
            {
                if ((this._SimPROJECT == null))
                {
                    this._SimPROJECT = base.CreateQuery<SimPROJECT>("SimPROJECT");
                }
                return this._SimPROJECT;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SimPROJECT> _SimPROJECT;
        /// <summary>
        /// Il n'existe aucun commentaire pour Users dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("Users");
                }
                return this._Users;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Users> _Users;
        /// <summary>
        /// Il n'existe aucun commentaire pour SimPROJECT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSimPROJECT(SimPROJECT simPROJECT)
        {
            base.AddObject("SimPROJECT", simPROJECT);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Users dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour ServerData.SimPROJECT dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SimPROJECT")]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SimPROJECT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet SimPROJECT.
        /// </summary>
        /// <param name="ID">Valeur initiale de Id.</param>
        /// <param name="hash">Valeur initiale de Hash.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SimPROJECT CreateSimPROJECT(int ID, string hash)
        {
            SimPROJECT simPROJECT = new SimPROJECT();
            simPROJECT.Id = ID;
            simPROJECT.Hash = hash;
            return simPROJECT;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Id dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Hash dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Hash
        {
            get
            {
                return this._Hash;
            }
            set
            {
                this.OnHashChanging(value);
                this._Hash = value;
                this.OnHashChanged();
                this.OnPropertyChanged("Hash");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Hash;
        partial void OnHashChanging(string value);
        partial void OnHashChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété IdProject dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> IdProject
        {
            get
            {
                return this._IdProject;
            }
            set
            {
                this.OnIdProjectChanging(value);
                this._IdProject = value;
                this.OnIdProjectChanged();
                this.OnPropertyChanged("IdProject");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _IdProject;
        partial void OnIdProjectChanging(global::System.Nullable<int> value);
        partial void OnIdProjectChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Version dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Version;
        partial void OnVersionChanging(global::System.Nullable<int> value);
        partial void OnVersionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Evolution dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Evolution
        {
            get
            {
                return this._Evolution;
            }
            set
            {
                this.OnEvolutionChanging(value);
                this._Evolution = value;
                this.OnEvolutionChanged();
                this.OnPropertyChanged("Evolution");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Evolution;
        partial void OnEvolutionChanging(string value);
        partial void OnEvolutionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété NomIDialog dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NomIDialog
        {
            get
            {
                return this._NomIDialog;
            }
            set
            {
                this.OnNomIDialogChanging(value);
                this._NomIDialog = value;
                this.OnNomIDialogChanged();
                this.OnPropertyChanged("NomIDialog");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NomIDialog;
        partial void OnNomIDialogChanging(string value);
        partial void OnNomIDialogChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Obsolete dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Obsolete
        {
            get
            {
                return this._Obsolete;
            }
            set
            {
                this.OnObsoleteChanging(value);
                this._Obsolete = value;
                this.OnObsoleteChanged();
                this.OnPropertyChanged("Obsolete");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Obsolete;
        partial void OnObsoleteChanging(global::System.Nullable<bool> value);
        partial void OnObsoleteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété IdMT dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IdMT
        {
            get
            {
                return this._IdMT;
            }
            set
            {
                this.OnIdMTChanging(value);
                this._IdMT = value;
                this.OnIdMTChanged();
                this.OnPropertyChanged("IdMT");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IdMT;
        partial void OnIdMTChanging(string value);
        partial void OnIdMTChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété IdMO dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IdMO
        {
            get
            {
                return this._IdMO;
            }
            set
            {
                this.OnIdMOChanging(value);
                this._IdMO = value;
                this.OnIdMOChanged();
                this.OnPropertyChanged("IdMO");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IdMO;
        partial void OnIdMOChanging(string value);
        partial void OnIdMOChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété IdSIM dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IdSIM
        {
            get
            {
                return this._IdSIM;
            }
            set
            {
                this.OnIdSIMChanging(value);
                this._IdSIM = value;
                this.OnIdSIMChanged();
                this.OnPropertyChanged("IdSIM");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IdSIM;
        partial void OnIdSIMChanging(string value);
        partial void OnIdSIMChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Date dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété MOType dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MOType
        {
            get
            {
                return this._MOType;
            }
            set
            {
                this.OnMOTypeChanging(value);
                this._MOType = value;
                this.OnMOTypeChanged();
                this.OnPropertyChanged("MOType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MOType;
        partial void OnMOTypeChanging(string value);
        partial void OnMOTypeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété MTType dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MTType
        {
            get
            {
                return this._MTType;
            }
            set
            {
                this.OnMTTypeChanging(value);
                this._MTType = value;
                this.OnMTTypeChanged();
                this.OnPropertyChanged("MTType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MTType;
        partial void OnMTTypeChanging(string value);
        partial void OnMTTypeChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour ServerData.Users dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Users : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Users.
        /// </summary>
        /// <param name="ID">Valeur initiale de ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Users CreateUsers(int ID)
        {
            Users users = new Users();
            users.ID = ID;
            return users;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ID dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété LastName dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété FirstName dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Password dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Sociaty dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sociaty
        {
            get
            {
                return this._Sociaty;
            }
            set
            {
                this.OnSociatyChanging(value);
                this._Sociaty = value;
                this.OnSociatyChanged();
                this.OnPropertyChanged("Sociaty");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sociaty;
        partial void OnSociatyChanging(string value);
        partial void OnSociatyChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Street dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Town dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Town
        {
            get
            {
                return this._Town;
            }
            set
            {
                this.OnTownChanging(value);
                this._Town = value;
                this.OnTownChanged();
                this.OnPropertyChanged("Town");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Town;
        partial void OnTownChanging(string value);
        partial void OnTownChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ZipCode dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ZipCode
        {
            get
            {
                return this._ZipCode;
            }
            set
            {
                this.OnZipCodeChanging(value);
                this._ZipCode = value;
                this.OnZipCodeChanged();
                this.OnPropertyChanged("ZipCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ZipCode;
        partial void OnZipCodeChanging(string value);
        partial void OnZipCodeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Phone dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété emailAdress dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string emailAdress
        {
            get
            {
                return this._emailAdress;
            }
            set
            {
                this.OnemailAdressChanging(value);
                this._emailAdress = value;
                this.OnemailAdressChanged();
                this.OnPropertyChanged("emailAdress");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _emailAdress;
        partial void OnemailAdressChanging(string value);
        partial void OnemailAdressChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété PasswordNeedChange dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> PasswordNeedChange
        {
            get
            {
                return this._PasswordNeedChange;
            }
            set
            {
                this.OnPasswordNeedChangeChanging(value);
                this._PasswordNeedChange = value;
                this.OnPasswordNeedChangeChanged();
                this.OnPropertyChanged("PasswordNeedChange");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _PasswordNeedChange = false;
        partial void OnPasswordNeedChangeChanging(global::System.Nullable<bool> value);
        partial void OnPasswordNeedChangeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété RegistryDate dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> RegistryDate
        {
            get
            {
                return this._RegistryDate;
            }
            set
            {
                this.OnRegistryDateChanging(value);
                this._RegistryDate = value;
                this.OnRegistryDateChanged();
                this.OnPropertyChanged("RegistryDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _RegistryDate;
        partial void OnRegistryDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRegistryDateChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété NextPasswordChange dans le schéma.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> NextPasswordChange
        {
            get
            {
                return this._NextPasswordChange;
            }
            set
            {
                this.OnNextPasswordChangeChanging(value);
                this._NextPasswordChange = value;
                this.OnNextPasswordChangeChanged();
                this.OnPropertyChanged("NextPasswordChange");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _NextPasswordChange;
        partial void OnNextPasswordChangeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnNextPasswordChangeChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
