//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAY.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string MOType { get; set; }
        public string MTType { get; set; }
        public string UserProjectName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
