//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAY.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMProject
    {
        public int Id { get; set; }
        public string Hash { get; set; }
        public int IdProject { get; set; }
        public int Version { get; set; }
        public string Evolution { get; set; }
        public string NomIDialog { get; set; }
        public bool Obsolete { get; set; }
        public string IdMT { get; set; }
        public string IdMO { get; set; }
        public System.DateTime Date { get; set; }
        public string IdSIM { get; set; }
        public string MOType { get; set; }
        public string MTType { get; set; }
    }
}
