//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OF_PROD_TRAITE
    {
        public long ID { get; set; }
        public string NMROF { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string STATUSTYPE { get; set; }
        public Nullable<int> QTRTHEORIQUE { get; set; }
        public string Alea { get; set; }
        public Nullable<long> OPERATEUR { get; set; }
        public string ILOT { get; set; }
        public string ITEMREF { get; set; }
        public Nullable<int> QTRREEL { get; set; }
        public Nullable<double> TEMPSTHEORIQUE { get; set; }
        public bool ISALIVE { get; set; }
        public double TEMPSSUPPL { get; set; }
        public string MFGDES { get; set; }
    }
}
