//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATEURS
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ANNIVERSAIRE { get; set; }
        public string POSTE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string SERVICE { get; set; }
        public string INITIAL { get; set; }
        public Nullable<bool> PRESTAT { get; set; }
        public Nullable<System.DateTime> FINCONTRAT { get; set; }
        public bool ANIMATEUR { get; set; }
    }
}
