//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDRE_FABRICATION_GENERE
    {
        public long ID { get; set; }
        public string NUM_OF { get; set; }
        public string NUM_COMMANDE_CLIENT { get; set; }
        public string REF_INDUSTRIELLE_MO { get; set; }
        public string REF_COMMERCIALE_MO { get; set; }
        public string REF_INDUSTRIELLE_MT { get; set; }
        public string REF_COMMERCIALE_MT { get; set; }
        public string REF_COMMERCIALE_SIM { get; set; }
        public string REF_FIRMWARE_MO { get; set; }
        public string REF_FIRMWARE_MT { get; set; }
        public string REF_COMMERCIALE_PACK { get; set; }
        public string OPTIONS_LOGICIELLES { get; set; }
        public string REF_FICHE_PERSO { get; set; }
        public string NUM_SERIE_PACK { get; set; }
        public Nullable<int> NB_PACK { get; set; }
        public Nullable<int> NB_MO { get; set; }
        public Nullable<int> NB_MT { get; set; }
        public Nullable<int> NB_SIM { get; set; }
        public Nullable<System.DateTime> DATE_GENERATION { get; set; }
        public string OPTION_MATERIEL_MO { get; set; }
        public string OPTION_MATERIEL_MT { get; set; }
        public string COMMANDE_SYNCHRO { get; set; }
        public Nullable<bool> GENERE { get; set; }
        public string MARCHE { get; set; }
        public bool MODIF_MANUEL { get; set; }
        public string VERSION_LOG { get; set; }
        public string NUM_LIGNE_CLIENT { get; set; }
        public Nullable<bool> FABRIQUE { get; set; }
    }
}
