//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_INSTALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACK_INSTALLE()
        {
            this.MO = new HashSet<MO>();
            this.MT = new HashSet<MT>();
            this.SIM = new HashSet<SIM>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_OF { get; set; }
        public string NUM_SERIE_PACK { get; set; }
        public string REF_COMMERCIALE_PACK { get; set; }
        public Nullable<int> NUM_ORDRE { get; set; }
        public Nullable<System.DateTime> DATE_PROGRAMMATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MO> MO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT> MT { get; set; }
        public virtual ORDRE_FABRICATION ORDRE_FABRICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIM> SIM { get; set; }
    }
}
