//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEGASE_PROD2Entities : DbContext
    {
        public PEGASE_PROD2Entities()
            : base("name=PEGASE_PROD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ORDRE_FABRICATION_GENERE> ORDRE_FABRICATION_GENERE { get; set; }
        public virtual DbSet<OF_PROD_TRAITE> OF_PROD_TRAITE { get; set; }
        public virtual DbSet<OPERATEURS> OPERATEURS { get; set; }
    }
}
