//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALPEGASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEGASE_PRODEntities : DbContext
    {
        public PEGASE_PRODEntities()
            : base("name=PEGASE_PRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MO> MO { get; set; }
        public virtual DbSet<MT> MT { get; set; }
        public virtual DbSet<ORDRE_FABRICATION> ORDRE_FABRICATION { get; set; }
        public virtual DbSet<PACK_INSTALLE> PACK_INSTALLE { get; set; }
        public virtual DbSet<SIM> SIM { get; set; }
    }
}
