//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL_Compteur_Mono
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMME_UD_UR_UCEntities1 : DbContext
    {
        public GAMME_UD_UR_UCEntities1()
            : base("name=GAMME_UD_UR_UCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPTEUR> COMPTEUR { get; set; }
        public virtual DbSet<TRACAFABUDE> TRACAFABUDE { get; set; }
    }
}
