//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_PEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDRE_FABRICATION_ETAPE
    {
        public long ID { get; set; }
        public Nullable<long> ID_OF { get; set; }
        public Nullable<long> ID_PACK_ENCOURS { get; set; }
    
        public virtual ORDRE_FABRICATION ORDRE_FABRICATION { get; set; }
        public virtual PACK_INSTALLE PACK_INSTALLE { get; set; }
    }
}
