//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_PEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDRE_FABRICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDRE_FABRICATION()
        {
            this.ORDRE_FABRICATION_ETAPE = new HashSet<ORDRE_FABRICATION_ETAPE>();
            this.PACK_INSTALLE = new HashSet<PACK_INSTALLE>();
        }
    
        public long ID { get; set; }
        public string NUM_OF { get; set; }
        public string NUM_COMMANDE_CLIENT { get; set; }
        public string REF_INDUSTRIELLE_MO { get; set; }
        public string REF_COMMERCIALE_MO { get; set; }
        public string REF_INDUSTRIELLE_MT { get; set; }
        public string REF_COMMERCIALE_MT { get; set; }
        public string REF_COMMERCIALE_SIM { get; set; }
        public string REF_FIRMWARE_MO { get; set; }
        public string REF_FIRMWARE_MT { get; set; }
        public string REF_COMMERCIALE_PACK { get; set; }
        public string OPTIONS_LOGICIELLES { get; set; }
        public string REF_FICHE_PERSO { get; set; }
        public string NUM_SERIE_PACK { get; set; }
        public int NB_PACK { get; set; }
        public int NB_MO { get; set; }
        public int NB_MT { get; set; }
        public int NB_SIM { get; set; }
        public Nullable<System.DateTime> DATE_PROGRAMMATION { get; set; }
        public string OPTION_MATERIEL_MO { get; set; }
        public string OPTION_MATERIEL_MT { get; set; }
        public string COMMANDE_SYNCHRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDRE_FABRICATION_ETAPE> ORDRE_FABRICATION_ETAPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACK_INSTALLE> PACK_INSTALLE { get; set; }
    }
}
