//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_PEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_INSTALLE_ETAPE
    {
        public long ID { get; set; }
        public Nullable<long> ID_PACK_INSTALLE { get; set; }
        public Nullable<long> ID_ETAPE_PACK { get; set; }
        public Nullable<System.DateTime> DATE_PASSAGE_ETAPE { get; set; }
        public Nullable<long> ID_PRODUIT_APPLICATION { get; set; }
        public Nullable<int> TYPE_PRODUIT_APPLICATION { get; set; }
        public Nullable<int> NB_ESSAI { get; set; }
        public Nullable<long> ID_RESULTAT_ESSAI { get; set; }
    
        public virtual PACK_INSTALLE PACK_INSTALLE { get; set; }
    }
}
