//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_PEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_INSTALLATION
    {
        public long ID { get; set; }
        public string NUM_COMMANDE_CLIENT { get; set; }
        public string NUM_AFFAIRE { get; set; }
        public Nullable<long> ID_CLIENT { get; set; }
    }
}
