//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_PEGASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIM()
        {
            this.SIM_ETAPE = new HashSet<SIM_ETAPE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_PACK_INSTALLE { get; set; }
        public string NUM_SERIE_SIM { get; set; }
        public Nullable<System.DateTime> DATE_FABRICATION { get; set; }
        public string REF_INDUSTRIELLE { get; set; }
        public Nullable<int> NUM_ORDRE { get; set; }
        public string NUM_SERIE_CARTE_TEST { get; set; }
    
        public virtual PACK_INSTALLE PACK_INSTALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIM_ETAPE> SIM_ETAPE { get; set; }
    }
}
