//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONIMMEDIATE
    {
        public long ID { get; set; }
        public long ID_QRQC { get; set; }
        public string ActionPourClient { get; set; }
        public string Pilote { get; set; }
        public Nullable<System.DateTime> Delai { get; set; }
        public string Status { get; set; }
    
        public virtual QRQC QRQC { get; set; }
    }
}
