//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIC_PROD
    {
        public long ID { get; set; }
        public short Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDeFin { get; set; }
        public short Pole { get; set; }
    
        public virtual AIC_POLE AIC_POLE { get; set; }
    }
}
