//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALEAS_OF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALEAS_OF()
        {
            this.ALEAS_OF_DETAILS = new HashSet<ALEAS_OF_DETAILS>();
        }
    
        public long ID { get; set; }
        public long ID_OF_PROD_TRAITE { get; set; }
        public Nullable<int> NMR_ALEA { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<long> Delai { get; set; }
        public Nullable<long> ID_OF_PROD_ORIG { get; set; }
        public Nullable<bool> IsAlwaysOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALEAS_OF_DETAILS> ALEAS_OF_DETAILS { get; set; }
        public virtual OF_PROD_TRAITE OF_PROD_TRAITE { get; set; }
    }
}
