//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMELIORATION
    {
        public long ID { get; set; }
        public long Nmr { get; set; }
        public System.DateTime Date { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public short Status { get; set; }
        public short Type { get; set; }
        public string Input { get; set; }
        public string Emetteur { get; set; }
        public string UrlImage { get; set; }
    }
}
