//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPADDRESS
    {
        public byte BPATYP_0 { get; set; }
        public string BPANUM_0 { get; set; }
        public string BPAADD_0 { get; set; }
        public string BPADES_0 { get; set; }
        public string BPABID_0 { get; set; }
        public byte BPAADDFLG_0 { get; set; }
        public string BPAADDLIG_0 { get; set; }
        public string BPAADDLIG_1 { get; set; }
        public string BPAADDLIG_2 { get; set; }
        public string POSCOD_0 { get; set; }
        public string CTY_0 { get; set; }
        public string SAT_0 { get; set; }
        public string CRY_0 { get; set; }
        public string CRYNAM_0 { get; set; }
        public string TEL_0 { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string TEL_3 { get; set; }
        public string TEL_4 { get; set; }
        public string FAX_0 { get; set; }
        public string MOB_0 { get; set; }
        public string WEB_0 { get; set; }
        public string WEB_1 { get; set; }
        public string WEB_2 { get; set; }
        public string WEB_3 { get; set; }
        public string WEB_4 { get; set; }
        public string FCYWEB_0 { get; set; }
        public string EXTNUM_0 { get; set; }
        public string XEXT2NUM_0 { get; set; }
        public int EXPNUM_0 { get; set; }
        public string XSRVFAC_0 { get; set; }
        public string CREUSR_0 { get; set; }
        public System.DateTime CREDAT_0 { get; set; }
        public int CRETIM_0 { get; set; }
        public string UPDUSR_0 { get; set; }
        public System.DateTime UPDDAT_0 { get; set; }
        public int UPDTIM_0 { get; set; }
        public string CRESTP_0 { get; set; }
        public string UPDSTP_0 { get; set; }
        public string IDTSGL_0 { get; set; }
        public string XEDICOD_0 { get; set; }
        public byte X4VALID_0 { get; set; }
        public byte X4ADREXP_0 { get; set; }
        public string X4EECNUM_0 { get; set; }
        public byte X4ADRFAB_0 { get; set; }
        public string YDEP_0 { get; set; }
        public int ROWID { get; set; }
    }
}
