//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEGASE_CHECKFPSEntities1 : DbContext
    {
        public PEGASE_CHECKFPSEntities1()
            : base("name=PEGASE_CHECKFPSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STATUSFPS> STATUSFPS { get; set; }
        public virtual DbSet<STATUSRELANCE> STATUSRELANCE { get; set; }
        public virtual DbSet<DELAIFPS> DELAIFPS { get; set; }
        public virtual DbSet<COMMENTAIRE> COMMENTAIRE { get; set; }
        public virtual DbSet<TRACACMD> TRACACMD { get; set; }
        public virtual DbSet<TRACACMDMONO> TRACACMDMONO { get; set; }
        public virtual DbSet<TRACA_CHANGE_GESTIONSTATUS> TRACA_CHANGE_GESTIONSTATUS { get; set; }
    }
}
