//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPTEUR
    {
        public long ID { get; set; }
        public string CODE_COMPTEUR { get; set; }
        public string LBL_COMPTEUR { get; set; }
        public string NEXT_NUM_CHRONO { get; set; }
        public int LONGUEUR_COMPTEUR { get; set; }
        public Nullable<int> TYPE_COMPTEUR { get; set; }
        public string CARACTERE_COMPLETION { get; set; }
    }
}
