//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_GENERIQUE
    {
        public long ID { get; set; }
        public string Champ { get; set; }
        public Nullable<System.DateTime> Datetime1 { get; set; }
        public Nullable<long> Value1 { get; set; }
        public Nullable<long> Value2 { get; set; }
        public string StringValue1 { get; set; }
        public string StringValue2 { get; set; }
        public Nullable<bool> Editable { get; set; }
    }
}
