//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMD_REASSORT
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idPiece { get; set; }
        public Nullable<int> operateur { get; set; }
        public Nullable<System.DateTime> traiteLe { get; set; }
        public string description { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<bool> dispo { get; set; }
    }
}
