//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENEMENT
    {
        public long ID { get; set; }
        public Nullable<short> TYPE_EVENEMENT { get; set; }
        public Nullable<System.DateTime> DATE_REPORT { get; set; }
        public string DESCRIPTION { get; set; }
        public string MESSAGE_ERREUR { get; set; }
        public string UTILISATEUR { get; set; }
    }
}
