//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHE_PACK_TRACABILITE
    {
        public long ID { get; set; }
        public Nullable<long> ID_PACK_INSTALLE { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT_VALIDITE { get; set; }
        public Nullable<System.DateTime> DATE_FIN_VALIDITE { get; set; }
        public Nullable<bool> ACTIF { get; set; }
        public string REF_FICHE_PERSO { get; set; }
        public Nullable<short> VERSION_STRUCTURE_MAJEUR { get; set; }
        public Nullable<short> VERSION_STRUCTURE_MINEUR { get; set; }
        public Nullable<short> VERSION_CONFIGURATION_STANDARD { get; set; }
        public Nullable<short> VERSION_CONFIGURATION_CLIENT { get; set; }
        public byte[] IDIALOG_FICHE_PERSO { get; set; }
        public string NOM_FICHIER { get; set; }
    
        public virtual PACK_INSTALLE PACK_INSTALLE { get; set; }
    }
}
