//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRC
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public bool Valide { get; set; }
        public string NmrFRC { get; set; }
        public string Nom { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Client { get; set; }
        public string NmrClient { get; set; }
        public string TypeProduit { get; set; }
        public string Commande { get; set; }
        public string Description { get; set; }
        public string Commentaire { get; set; }
        public string Action { get; set; }
        public string StatusFRC { get; set; }
        public string Service { get; set; }
        public bool StatusBDD { get; set; }
    }
}
