//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMME_UD_UR_UCEntities : DbContext
    {
        public GAMME_UD_UR_UCEntities()
            : base("name=GAMME_UD_UR_UCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRACAFABUDE> TRACAFABUDE { get; set; }
        public virtual DbSet<TRACACODEID> TRACACODEID { get; set; }
        public virtual DbSet<TRACA_PROGRAMMATION> TRACA_PROGRAMMATION { get; set; }
        public virtual DbSet<TRACAFABUDR> TRACAFABUDR { get; set; }
        public virtual DbSet<UDE> UDE { get; set; }
        public virtual DbSet<UDR> UDR { get; set; }
        public virtual DbSet<URE> URE { get; set; }
        public virtual DbSet<URR> URR { get; set; }
    }
}
