//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIQUE_CONTROL
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RawScan { get; set; }
        public string NumOF { get; set; }
        public Nullable<int> NumPack { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<long> Operateur { get; set; }
        public Nullable<bool> IsPack { get; set; }
    }
}
