//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_LOCALISATION
    {
        public long ID { get; set; }
        public string ITEMREF { get; set; }
        public string Chariot { get; set; }
        public Nullable<int> QtrByBox { get; set; }
        public Nullable<int> NbBacPourImpression { get; set; }
    }
}
