//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMME_KEPLEREntities : DbContext
    {
        public GAMME_KEPLEREntities()
            : base("name=GAMME_KEPLEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPTEUR> COMPTEUR { get; set; }
        public virtual DbSet<MOMT> MOMT { get; set; }
        public virtual DbSet<ORDRE_FABRICATION_KEPLER> ORDRE_FABRICATION { get; set; }
        public virtual DbSet<TRACA_ETAPE_FAB> TRACA_ETAPE_FAB { get; set; }
    }
}
