//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_PROD
    {
        public long ID { get; set; }
        public short Annee { get; set; }
        public short Semaine { get; set; }
        public double OTDByWeek { get; set; }
        public double OTRByWeek { get; set; }
        public System.DateTime DatetimeMiseAJour { get; set; }
        public int CA { get; set; }
        public Nullable<double> ObjectifOTR { get; set; }
        public Nullable<double> ObjectifOTD { get; set; }
    }
}
