//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_CA
    {
        public long ID { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<int> CA { get; set; }
        public Nullable<int> EntreeCmd { get; set; }
    }
}
