//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_STC
    {
        public long ID { get; set; }
        public Nullable<long> ID_STC { get; set; }
        public Nullable<int> Semaine { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<double> Value1 { get; set; }
        public Nullable<double> Value2 { get; set; }
        public Nullable<double> Value3 { get; set; }
        public Nullable<double> Value4 { get; set; }
        public Nullable<double> Value5 { get; set; }
        public Nullable<double> Value6 { get; set; }
        public Nullable<double> Value7 { get; set; }
        public Nullable<double> Value8 { get; set; }
        public Nullable<double> Value9 { get; set; }
        public Nullable<double> Value10 { get; set; }
        public Nullable<double> Value11 { get; set; }
        public Nullable<double> Value12 { get; set; }
        public Nullable<double> Value13 { get; set; }
        public Nullable<double> Value14 { get; set; }
        public Nullable<double> Value15 { get; set; }
        public Nullable<double> Value16 { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
    }
}
