//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOMT
    {
        public long IDMOMT { get; set; }
        public long ID_ORDRE_FABRICATION { get; set; }
        public string REF_COM { get; set; }
        public string CODEID { get; set; }
        public string NMR_SERIE { get; set; }
        public string NMR_SERIE_HARD { get; set; }
        public Nullable<System.DateTime> DATE_PROGRAMMATION { get; set; }
        public Nullable<bool> IsMO { get; set; }
    
        public virtual ORDRE_FABRICATION_KEPLER ORDRE_FABRICATION { get; set; }
    }
}
