//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MT()
        {
            this.MT_ETAPE = new HashSet<MT_ETAPE>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_PACK_INSTALLE { get; set; }
        public string NUM_SERIE_MT { get; set; }
        public string CODE_IDENTITE_NATIF { get; set; }
        public Nullable<int> CODE_IDENTITE_APPRENTISSAGE { get; set; }
        public Nullable<System.DateTime> DATE_FABRICATION { get; set; }
        public string CODE_ARTICLE_LOGICIEL { get; set; }
        public string VERSION_LOGICIELLE { get; set; }
        public Nullable<System.DateTime> DATE_DERNIERE_MAJ { get; set; }
        public string REF_INDUSTRIELLE { get; set; }
        public Nullable<int> NUM_ORDRE { get; set; }
        public string NUM_SERIE_CARTE_TEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT_ETAPE> MT_ETAPE { get; set; }
        public virtual PACK_INSTALLE PACK_INSTALLE { get; set; }
    }
}
