//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NON_CONFORMITE
    {
        public long ID { get; set; }
        public long NmrChrono { get; set; }
        public string NmrChronoS { get; set; }
        public Nullable<long> OperateursID { get; set; }
        public string Item { get; set; }
        public string DescriptionItem { get; set; }
        public string DescriptionUser { get; set; }
        public Nullable<int> Qtr { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string NmrOF { get; set; }
        public int Status { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
        public virtual STATUS_PNC STATUS_PNC { get; set; }
    }
}
