//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OF_PROD_TRAITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OF_PROD_TRAITE()
        {
            this.ALEAS_OF = new HashSet<ALEAS_OF>();
        }
    
        public long ID { get; set; }
        public string NMROF { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string STATUSTYPE { get; set; }
        public Nullable<int> QTRTHEORIQUE { get; set; }
        public string Alea { get; set; }
        public Nullable<long> OPERATEUR { get; set; }
        public string ILOT { get; set; }
        public string ITEMREF { get; set; }
        public Nullable<int> QTRREEL { get; set; }
        public Nullable<double> TEMPSTHEORIQUE { get; set; }
        public bool ISALIVE { get; set; }
        public double TEMPSSUPPL { get; set; }
        public string MFGDES { get; set; }
        public string TCLCOD_0 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALEAS_OF> ALEAS_OF { get; set; }
    }
}
