//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERATEURS()
        {
            this.KPI_STC = new HashSet<KPI_STC>();
            this.NON_CONFORMITE = new HashSet<NON_CONFORMITE>();
            this.TEMPS_SEMAINE = new HashSet<TEMPS_SEMAINE>();
            this.PLANNING_OPERATEUR = new HashSet<PLANNING_OPERATEUR>();
            this.POLES = new HashSet<POLES>();
            this.SERENITE = new HashSet<SERENITE>();
            this.TEMPS_SAISI = new HashSet<TEMPS_SAISI>();
            this.CONTROLE_QUALITE = new HashSet<CONTROLE_QUALITE>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> ANNIVERSAIRE { get; set; }
        public Nullable<int> POLE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string SERVICE { get; set; }
        public string INITIAL { get; set; }
        public Nullable<bool> PRESTAT { get; set; }
        public Nullable<System.DateTime> FINCONTRAT { get; set; }
        public bool ANIMATEUR { get; set; }
        public string PATHA { get; set; }
        public string PATHB { get; set; }
        public string SousService { get; set; }
        public Nullable<double> HoraireByWeek { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public string Matricule { get; set; }
        public Nullable<bool> isValidPasswd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_STC> KPI_STC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NON_CONFORMITE> NON_CONFORMITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPS_SEMAINE> TEMPS_SEMAINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLES> POLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERENITE> SERENITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPS_SAISI> TEMPS_SAISI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLE_QUALITE> CONTROLE_QUALITE { get; set; }
        public virtual OPERATEURS_PWD OPERATEURS_PWD { get; set; }
    }
}
