//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDRE_FABRICATION_KEPLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDRE_FABRICATION_KEPLER()
        {
            this.MOMT = new HashSet<MOMT>();
        }
    
        public long ID { get; set; }
        public string NUM_OF { get; set; }
        public string NUM_COMMANDE_CLIENT { get; set; }
        public string REF_COMMERCIAL_PACK { get; set; }
        public string REF_COMMERCIAL_MT { get; set; }
        public string REF_COMMERCIAL_MO { get; set; }
        public string REF_FIRMWARE_MO { get; set; }
        public string REF_FIRMWARE_MT { get; set; }
        public int NB_PACK { get; set; }
        public int NB_MT { get; set; }
        public int NB_MO { get; set; }
        public Nullable<System.DateTime> DATE_PROGRAMMATION { get; set; }
        public Nullable<int> NMRORDRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOMT> MOMT { get; set; }
    }
}
