//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_COMMANDES_FOURNISSEUR
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string NaturePB { get; set; }
        public string Probleme { get; set; }
        public Nullable<bool> Resolution { get; set; }
    }
}
