//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANIF_OF
    {
        public long ID { get; set; }
        public string NumOF { get; set; }
        public long Pole { get; set; }
        public Nullable<System.DateTime> DatePlanif { get; set; }
        public int Etat { get; set; }
        public int Rang { get; set; }
        public Nullable<double> ChargeTheorique { get; set; }
        public Nullable<double> ChargeReel { get; set; }
    }
}
