//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANIFICATION_OF
    {
        public long ID { get; set; }
        public string NMROF { get; set; }
        public Nullable<long> Operateur { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> NmrOrdre { get; set; }
        public Nullable<System.DateTime> DateCloture { get; set; }
        public Nullable<bool> Validite { get; set; }
    }
}
