//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNING_OPERATEUR
    {
        public long ID { get; set; }
        public long ID_STC { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Semaine { get; set; }
        public Nullable<short> LundiMatin { get; set; }
        public Nullable<short> LundiApresmidi { get; set; }
        public Nullable<short> MardiMatin { get; set; }
        public Nullable<short> MardiApresmidi { get; set; }
        public Nullable<short> MercrediMatin { get; set; }
        public Nullable<short> MercrediApresmidi { get; set; }
        public Nullable<short> JeudiMatin { get; set; }
        public Nullable<short> JeudiApresmidi { get; set; }
        public Nullable<short> VendrediMatin { get; set; }
        public Nullable<short> VendrediApresmidi { get; set; }
        public Nullable<short> SamediMatin { get; set; }
        public Nullable<short> SamediApresmidi { get; set; }
        public Nullable<short> DimancheMatin { get; set; }
        public Nullable<short> DimancheApresmidi { get; set; }
        public Nullable<bool> Conflit { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE1 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE2 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE3 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE4 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE5 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE6 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE7 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE8 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE9 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE10 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE11 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE12 { get; set; }
        public virtual PLANNING_VALUE PLANNING_VALUE13 { get; set; }
    }
}
