//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNING_VALUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANNING_VALUE()
        {
            this.PLANNING_OPERATEUR = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR1 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR2 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR3 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR4 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR5 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR6 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR7 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR8 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR9 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR10 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR11 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR12 = new HashSet<PLANNING_OPERATEUR>();
            this.PLANNING_OPERATEUR13 = new HashSet<PLANNING_OPERATEUR>();
        }
    
        public short ID { get; set; }
        public string Status { get; set; }
        public short Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANNING_OPERATEUR> PLANNING_OPERATEUR13 { get; set; }
    }
}
