//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEGASE_PROD2Entities2 : DbContext
    {
        public PEGASE_PROD2Entities2()
            : base("name=PEGASE_PROD2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIDENT> ACCIDENT { get; set; }
        public virtual DbSet<ACTIONIMMEDIATE> ACTIONIMMEDIATE { get; set; }
        public virtual DbSet<AIC_EQUIPE> AIC_EQUIPE { get; set; }
        public virtual DbSet<AIC_POLE> AIC_POLE { get; set; }
        public virtual DbSet<AIC_PROD> AIC_PROD { get; set; }
        public virtual DbSet<ALEAS_OF> ALEAS_OF { get; set; }
        public virtual DbSet<ALEAS_OF_DETAILS> ALEAS_OF_DETAILS { get; set; }
        public virtual DbSet<AMELIORATION> AMELIORATION { get; set; }
        public virtual DbSet<DATA_GENERIQUE> DATA_GENERIQUE { get; set; }
        public virtual DbSet<FRC> FRC { get; set; }
        public virtual DbSet<KPI_CA> KPI_CA { get; set; }
        public virtual DbSet<KPI_PROD> KPI_PROD { get; set; }
        public virtual DbSet<KPI_STC> KPI_STC { get; set; }
        public virtual DbSet<NON_CONFORMITE> NON_CONFORMITE { get; set; }
        public virtual DbSet<NON_DETECTION> NON_DETECTION { get; set; }
        public virtual DbSet<OCCURRENCE> OCCURRENCE { get; set; }
        public virtual DbSet<OF_PROD_TRAITE> OF_PROD_TRAITE { get; set; }
        public virtual DbSet<OPERATEURS> OPERATEURS { get; set; }
        public virtual DbSet<ORDRE_FABRICATION_GENERE> ORDRE_FABRICATION_GENERE { get; set; }
        public virtual DbSet<PLANIF_OF> PLANIF_OF { get; set; }
        public virtual DbSet<PLANIFICATION_OF> PLANIFICATION_OF { get; set; }
        public virtual DbSet<PLANNING_OPERATEUR> PLANNING_OPERATEUR { get; set; }
        public virtual DbSet<PLANNING_VALUE> PLANNING_VALUE { get; set; }
        public virtual DbSet<POLES> POLES { get; set; }
        public virtual DbSet<POSTES> POSTES { get; set; }
        public virtual DbSet<QRQC> QRQC { get; set; }
        public virtual DbSet<QUESTIONS_QRQC> QUESTIONS_QRQC { get; set; }
        public virtual DbSet<SERENITE> SERENITE { get; set; }
        public virtual DbSet<SOLUTION_DURABLE> SOLUTION_DURABLE { get; set; }
        public virtual DbSet<SOUSPROJET> SOUSPROJET { get; set; }
        public virtual DbSet<STATUS_PNC> STATUS_PNC { get; set; }
        public virtual DbSet<SUIVI_OFFRE> SUIVI_OFFRE { get; set; }
        public virtual DbSet<TEMPS_SAISI> TEMPS_SAISI { get; set; }
        public virtual DbSet<TEMPS_SEMAINE> TEMPS_SEMAINE { get; set; }
        public virtual DbSet<TEST_OF> TEST_OF { get; set; }
        public virtual DbSet<TEST_OPERATION> TEST_OPERATION { get; set; }
        public virtual DbSet<TRACABILITE> TRACABILITE { get; set; }
        public virtual DbSet<CONTROLE_QUALITE> CONTROLE_QUALITE { get; set; }
        public virtual DbSet<TYPE_ANOMALIE> TYPE_ANOMALIE { get; set; }
        public virtual DbSet<TYPE_CAUSE> TYPE_CAUSE { get; set; }
    }
}
