//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWD_TOKEN
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
    }
}
