//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRQC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRQC()
        {
            this.ACTIONIMMEDIATE = new HashSet<ACTIONIMMEDIATE>();
            this.NON_DETECTION = new HashSet<NON_DETECTION>();
            this.OCCURRENCE = new HashSet<OCCURRENCE>();
            this.QUESTIONS_QRQC = new HashSet<QUESTIONS_QRQC>();
            this.SOLUTION_DURABLE = new HashSet<SOLUTION_DURABLE>();
        }
    
        public long ID { get; set; }
        public System.DateTime DateOuverture { get; set; }
        public Nullable<System.DateTime> DateCloture { get; set; }
        public Nullable<System.DateTime> DateSuivis { get; set; }
        public string Participants { get; set; }
        public string Pilote { get; set; }
        public string Origine { get; set; }
        public string DescriptionProcess { get; set; }
        public string UrlImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIONIMMEDIATE> ACTIONIMMEDIATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NON_DETECTION> NON_DETECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCCURRENCE> OCCURRENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONS_QRQC> QUESTIONS_QRQC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLUTION_DURABLE> SOLUTION_DURABLE { get; set; }
    }
}
