//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERENITE
    {
        public long index { get; set; }
        public long ID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int NiveauSerenite { get; set; }
        public Nullable<int> NiveauSerenite2 { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
    }
}
