//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUSPROJET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOUSPROJET()
        {
            this.TEMPS_SAISI = new HashSet<TEMPS_SAISI>();
        }
    
        public long ID { get; set; }
        public long IDSOUSPROJET { get; set; }
        public string NomSousProjet { get; set; }
        public bool Affichage { get; set; }
        public Nullable<System.DateTime> DateFinProjet { get; set; }
        public string TitreSousProjet { get; set; }
        public string Service { get; set; }
        public string Commentaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPS_SAISI> TEMPS_SAISI { get; set; }
    }
}
