//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQUOTED
    {
        public string SQHNUM_0 { get; set; }
        public int SQDLIN_0 { get; set; }
        public string CPY_0 { get; set; }
        public string SALFCY_0 { get; set; }
        public string BPCORD_0 { get; set; }
        public System.DateTime QUODAT_0 { get; set; }
        public short DAYLTI_0 { get; set; }
        public string ITMREF_0 { get; set; }
        public string ITMDES1_0 { get; set; }
        public string ITMDES_0 { get; set; }
        public string VACITM_0 { get; set; }
        public string VACITM_1 { get; set; }
        public string VACITM_2 { get; set; }
        public string REP1_0 { get; set; }
        public decimal REPRAT1_0 { get; set; }
        public string REP2_0 { get; set; }
        public decimal REPRAT2_0 { get; set; }
        public decimal REPCOE_0 { get; set; }
        public decimal GROPRI_0 { get; set; }
        public short PRIREN_0 { get; set; }
        public decimal NETPRI_0 { get; set; }
        public decimal PFM_0 { get; set; }
        public decimal NETPRINOT_0 { get; set; }
        public decimal NETPRIATI_0 { get; set; }
        public decimal CPRPRI_0 { get; set; }
        public decimal DISCRGVAL1_0 { get; set; }
        public decimal DISCRGVAL2_0 { get; set; }
        public decimal DISCRGVAL3_0 { get; set; }
        public decimal DISCRGVAL4_0 { get; set; }
        public decimal DISCRGVAL5_0 { get; set; }
        public decimal DISCRGVAL6_0 { get; set; }
        public decimal DISCRGVAL7_0 { get; set; }
        public decimal DISCRGVAL8_0 { get; set; }
        public decimal DISCRGVAL9_0 { get; set; }
        public short DISCRGREN1_0 { get; set; }
        public short DISCRGREN2_0 { get; set; }
        public short DISCRGREN3_0 { get; set; }
        public short DISCRGREN4_0 { get; set; }
        public short DISCRGREN5_0 { get; set; }
        public short DISCRGREN6_0 { get; set; }
        public short DISCRGREN7_0 { get; set; }
        public short DISCRGREN8_0 { get; set; }
        public short DISCRGREN9_0 { get; set; }
        public string VAT_0 { get; set; }
        public string VAT_1 { get; set; }
        public string VAT_2 { get; set; }
        public decimal CLCAMT1_0 { get; set; }
        public decimal CLCAMT2_0 { get; set; }
        public byte DSPLINFLG_0 { get; set; }
        public short DDTANUM_0 { get; set; }
        public short DDTANUM_1 { get; set; }
        public short DDTANUM_2 { get; set; }
        public short DDTANUM_3 { get; set; }
        public short DDTANUM_4 { get; set; }
        public short DDTANUM_5 { get; set; }
        public short DDTANUM_6 { get; set; }
        public short DDTANUM_7 { get; set; }
        public short DDTANUM_8 { get; set; }
        public decimal DDTANOT_0 { get; set; }
        public decimal DDTANOT_1 { get; set; }
        public decimal DDTANOT_2 { get; set; }
        public decimal DDTANOT_3 { get; set; }
        public decimal DDTANOT_4 { get; set; }
        public decimal DDTANOT_5 { get; set; }
        public decimal DDTANOT_6 { get; set; }
        public decimal DDTANOT_7 { get; set; }
        public decimal DDTANOT_8 { get; set; }
        public decimal QTY_0 { get; set; }
        public string SAU_0 { get; set; }
        public string STU_0 { get; set; }
        public decimal SAUSTUCOE_0 { get; set; }
        public string BPAADD_0 { get; set; }
        public string STOFCY_0 { get; set; }
        public string CNDNAM_0 { get; set; }
        public byte LINTYP_0 { get; set; }
        public byte FOCFLG_0 { get; set; }
        public int ORILIN_0 { get; set; }
        public string SOHNUM_0 { get; set; }
        public int SOPLIN_0 { get; set; }
        public byte ORDFLG_0 { get; set; }
        public decimal ORDQTY_0 { get; set; }
        public string SQDTEX_0 { get; set; }
        public string GEOCOD_0 { get; set; }
        public string INSCTYFLG_0 { get; set; }
        public string VTS_0 { get; set; }
        public string VTC_0 { get; set; }
        public string TAXGEOFLG_0 { get; set; }
        public short TAXFLG_0 { get; set; }
        public short TAXREGFLG_0 { get; set; }
        public decimal RATTAXLIN_0 { get; set; }
        public decimal BASTAXLIN_0 { get; set; }
        public byte OCNPRNBOM_0 { get; set; }
        public byte NDEPRNBOM_0 { get; set; }
        public byte INVPRNBOM_0 { get; set; }
        public int EXPNUM_0 { get; set; }
        public short XFLAGLM_0 { get; set; }
        public decimal DSPLINWEI_0 { get; set; }
        public decimal DSPLINVOL_0 { get; set; }
        public string XQUONUM_0 { get; set; }
        public string DSPWEU_0 { get; set; }
        public string DSPVOU_0 { get; set; }
        public int IMPNUMLIG_0 { get; set; }
        public string CREUSR_0 { get; set; }
        public System.DateTime CREDAT_0 { get; set; }
        public string UPDUSR_0 { get; set; }
        public System.DateTime UPDDAT_0 { get; set; }
        public string ZMAPPLI_0 { get; set; }
        public int ROWID { get; set; }
        public int UPDTICK_0 { get; set; }
        public string ECCVALMAJ_0 { get; set; }
        public string ECCVALMIN_0 { get; set; }
        public string PJT_0 { get; set; }
        public string SSTCOD_0 { get; set; }
        public string ZIDWEB_0 { get; set; }
        public byte DLVFLG_0 { get; set; }
        public System.DateTime CREDATTIM_0 { get; set; }
        public System.DateTime UPDDATTIM_0 { get; set; }
        public byte[] AUUID_0 { get; set; }
        public string SQDPSONUM_0 { get; set; }
        public short SQDSEQNUM_0 { get; set; }
        public short LINREVNUM_0 { get; set; }
        public string X4RGOPL_0 { get; set; }
        public string XDESTFIN_0 { get; set; }
        public string XDESINT_0 { get; set; }
        public short X4FACTURE_0 { get; set; }
        public short X4SAVLIV_0 { get; set; }
    }
}
