//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUIVI_OFFRE
    {
        public long ID { get; set; }
        public string SQHNUM { get; set; }
        public Nullable<System.DateTime> DateRelance { get; set; }
        public Nullable<bool> Relance { get; set; }
    }
}
