//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPS_SAISI
    {
        public long ID { get; set; }
        public short Annee { get; set; }
        public short Semaine { get; set; }
        public long SOUSPROJET_ID { get; set; }
        public double Days1 { get; set; }
        public double Days2 { get; set; }
        public double Days3 { get; set; }
        public double Days4 { get; set; }
        public double Days5 { get; set; }
        public double Days6 { get; set; }
        public double Days7 { get; set; }
        public bool Complete { get; set; }
        public long OPERATEURS_ID { get; set; }
    
        public virtual OPERATEURS OPERATEURS { get; set; }
        public virtual SOUSPROJET SOUSPROJET { get; set; }
    }
}
