//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_OPERATION
    {
        public string NumOpe { get; set; }
        public string NumOF { get; set; }
        public int Ordre { get; set; }
        public string Description { get; set; }
    
        public virtual TEST_OF TEST_OF { get; set; }
    }
}
