//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACABILITE_BL
    {
        public long ID { get; set; }
        public string NmrOF { get; set; }
        public string NmrCmd { get; set; }
        public string NmrPack { get; set; }
        public string logged { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> FirstTimeStart { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<int> NbColis { get; set; }
        public Nullable<int> NbOFBycolis { get; set; }
        public Nullable<int> NbArtByBl { get; set; }
        public string Transporteur { get; set; }
        public string PaysDest { get; set; }
        public Nullable<System.DateTime> TimeSendRequested { get; set; }
        public Nullable<System.DateTime> TimeSendPlan { get; set; }
    }
}
