//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACABILITE
    {
        public long ID { get; set; }
        public string NmrOF { get; set; }
        public string NmrPack { get; set; }
        public Nullable<int> logged { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
