//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACA_PROGRAMMATION
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> OF_DateTime { get; set; }
        public string OF_Commande { get; set; }
        public string OF_NmrOF { get; set; }
        public Nullable<int> OF_Nmrordre { get; set; }
        public Nullable<int> OF_Quantite { get; set; }
        public string OF_RefProduit { get; set; }
        public string OF_Cplref { get; set; }
        public string OF_Fperso { get; set; }
        public string OF_CodeID { get; set; }
        public string OF_RassoRX { get; set; }
        public string OF_RassoTX { get; set; }
        public string OF_CONF_BTS { get; set; }
        public string OF_Cle { get; set; }
        public string OF_APASS { get; set; }
        public string OF_Canal1 { get; set; }
        public string OF_Canal2 { get; set; }
        public string OF_CplCle { get; set; }
    }
}
