//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACA_ETAPE_FAB
    {
        public long ID { get; set; }
        public string NUM_OF { get; set; }
        public Nullable<long> NMR_ORDRE { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string ACTION { get; set; }
        public string PARAMS1 { get; set; }
        public string PARAMS2 { get; set; }
        public string PARAMS3 { get; set; }
    }
}
