//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACA_CHANGE_GESTIONSTATUS
    {
        public long ID { get; set; }
        public long ID_TRACACMD { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<short> Status { get; set; }
        public string STC { get; set; }
        public string ErreurStatusList { get; set; }
    
        public virtual TRACACMD TRACACMD { get; set; }
    }
}
