//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACAFABUDR
    {
        public long INDEXREF { get; set; }
        public string REFERENCE { get; set; }
        public string NMRSERIE { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public Nullable<short> QTROF { get; set; }
        public string CODEID { get; set; }
        public string NMRCLE { get; set; }
        public Nullable<bool> ISCLE { get; set; }
        public Nullable<bool> ISMT { get; set; }
    }
}
