//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACA_ETIQUETTES
    {
        public long ID { get; set; }
        public string TYPE_ETIQUETTE { get; set; }
        public string QTR { get; set; }
        public string ITEM { get; set; }
        public string REFERENCE1 { get; set; }
        public string REFERENCE2 { get; set; }
        public string LOT { get; set; }
        public string CMD { get; set; }
        public string NMR_OF { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<long> ID_OPE { get; set; }
    }
}
