//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurDFUSafir.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZCONFPACK4
    {
        public string ZOF_0 { get; set; }
        public string ZNOSERIEP_0 { get; set; }
        public string ZNOCDECLI_0 { get; set; }
        public decimal ZQTE_0 { get; set; }
        public string ZREFCOMPAK_0 { get; set; }
        public string ZREFFICHPACK_0 { get; set; }
        public string ZFPA_0 { get; set; }
        public string ZFPS_0 { get; set; }
        public int ZFICHSTD_0 { get; set; }
        public Nullable<int> ZQTESIM_0 { get; set; }
        public string ZREFCOMSIM_0 { get; set; }
        public Nullable<int> ZQTEMOPACK_0 { get; set; }
        public Nullable<int> ZQTEMTPACK_0 { get; set; }
        public string ZREFINDUSMO_0 { get; set; }
        public string ZREFINDUSMT_0 { get; set; }
        public string ZREFCOMMO_0 { get; set; }
        public string ZREFCOMMT_0 { get; set; }
        public string ZREFFIRMMO_0 { get; set; }
        public string ZREFFIRMMT_0 { get; set; }
        public string CFGFLDALP1_0 { get; set; }
        public string CFGFLDALP2_0 { get; set; }
        public string CFGFLDALP3_0 { get; set; }
        public string CFGFLDALP4_0 { get; set; }
        public string ZCDESYNCH_0 { get; set; }
        public string ZCARACTSERIE_0 { get; set; }
        public string ZCFGLIN_0 { get; set; }
        public string ZVERSION_0 { get; set; }
    }
}
